# Site settings
title: dati.lab.tp.it
remote_theme: timwis/jkan@main

# Nav bar
navigation:
  - title: Datasets
    url: /datasets/
  - title: Organizations
    url: /organizations/
  - title: Categories
    url: /categories/

# Collections
collections:
  datasets:
    output: true
    permalink: /datasets/:path/
  organizations:
    output: true
    permalink: /organizations/:path/
  dataset_categories:
    output: true
    permalink: /categories/:path/

# Collections (cont'd)
defaults:
  - scope:
      path: ""
      type: dataset_categories
    values:
      layout: category
  - scope:
      path: ""
      type: datasets
    values:
      layout: dataset
      category: Uncategorized
      organization: N/A
  - scope:
      path: ""
      type: organizations
    values:
      layout: organization

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Exclude from processing.
exclude:
  - .bundle/
  - _config.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - Makefile
